spring:
  spring:
    profiles:
      active: local
  data:
    mongodb:
      hosts: localhost
      port: 27018
      database: Kalah
      tls:
        enabled: false
kalah:
  initialNumberOfStones: 6

server:
  port: 80



